const QUERY_KEY_ACCOUNT = {
  GET_ALL_UNIT: 'QUERY_KEY_ACCOUNT_UNIT',
  GET_ALL_CUSTOMMER: 'QUERY_KEY_ACCOUNT_CUSTOMMER',
};
const QUERY_KEY_ATTRACTION = {
  GET_ALL: 'QUERY_KEY_ATTRACTION_GET_ALL',
  DETAIL: 'QUERY_KEY_ATTRACTION_DETAIL',
  TOTAL: 'QUERY_KEY_ATTRACTION_TOTAL',
};

const QUERY_KEY_HOTEL = {
  DETAIL: 'QUERY_KEY_HOTEL_DETAIL',
  GET_ALL: 'QUERY_KEY_HOTEL_GET_ALL',
  TOTAL: 'QUERY_KEY_HOTEL_TOTAL',
};
const QUERY_KEY_USER = {
  DETAIL: 'QUERY_KEY_USER_DETAIL',
  GET_ALL: 'QUERY_KEY_USER_GET_USER',
  GET_ALL_CUSTOMMER: 'QUERY_KEY_USER_GET_ALL_CUSTOMMER',
};
const QUERY_KEY_BLOG = {
  DETAIL: 'QUERY_KEY_BLOG_DETAIL',
  GET_ALL: 'QUERY_KEY_BLOG_GET_ALL',
};
const QUERY_KEY_BOOKING = {
  GET_ALL_ATTRACTION: 'QUERY_KEY_GET_ALL_BOOKING_ATTRACTION',
  GET_ALL_HOTEL: 'QUERY_KEY_GET_ALL_BOOKING_HOTEL',
};
export {
  QUERY_KEY_ACCOUNT,
  QUERY_KEY_ATTRACTION,
  QUERY_KEY_HOTEL,
  QUERY_KEY_USER,
  QUERY_KEY_BLOG,
  QUERY_KEY_BOOKING,
};
