const QUERY_KEY_ACCOUNT = {
  GET_ALL_UNIT: 'QUERY_KEY_ACCOUNT_UNIT',
  GET_ALL_CUSTOMMER: 'QUERY_KEY_ACCOUNT_CUSTOMMER',
};
const QUERY_KEY_ATTRACTION = {
  GET_ALL: 'QUERY_KEY_ATTRACTION_GET_ALL',
  DETAIL: 'QUERY_KEY_ATTRACTION_DETAIL',
};

const QUERY_KEY_HOTEL = {
  DETAIL: 'QUERY_KEY_HOTEL_DETAIL',
  GET_ALL: 'QUERY_KEY_HOTEL_GET_ALL',
};
const QUERY_KEY_USER = {
  DETAIL: 'QUERY_KEY_USER_DETAIL',
  GET_ALL: 'QUERY_KEY_USER_GET_USER',
  GET_ALL_CUSTOMMER: 'QUERY_KEY_USER_GET_ALL_CUSTOMMER',
};
export {
  QUERY_KEY_ACCOUNT,
  QUERY_KEY_ATTRACTION,
  QUERY_KEY_HOTEL,
  QUERY_KEY_USER,
};
